-- 경제 캘린더 테이블 생성 (이슈 #35)
CREATE TABLE economic_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(500)  NOT NULL,
    description TEXT,
    event_date  TIMESTAMP     NOT NULL,
    country     VARCHAR(10)   NOT NULL,
    importance  VARCHAR(20)   NOT NULL,
    actual      VARCHAR(100),
    forecast    VARCHAR(100),
    previous    VARCHAR(100),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_economic_events_event_date ON economic_events (event_date);
CREATE INDEX idx_economic_events_country ON economic_events (country);

-- 2026년 주요 경제 이벤트 시드 데이터
INSERT INTO economic_events (title, description, event_date, country, importance) VALUES
-- FOMC 회의 일정 (2026년)
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-01-28 19:00:00', 'US', 'HIGH'),
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-03-18 18:00:00', 'US', 'HIGH'),
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-05-06 18:00:00', 'US', 'HIGH'),
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-06-17 18:00:00', 'US', 'HIGH'),
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-07-29 18:00:00', 'US', 'HIGH'),
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-09-16 18:00:00', 'US', 'HIGH'),
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-11-04 18:00:00', 'US', 'HIGH'),
('FOMC 금리 결정', 'FOMC 통화정책 회의 결과 발표', '2026-12-16 19:00:00', 'US', 'HIGH'),

-- 미국 CPI 발표 (2026년 월별)
('US CPI 발표', '미국 소비자물가지수 발표', '2026-01-14 13:30:00', 'US', 'HIGH'),
('US CPI 발표', '미국 소비자물가지수 발표', '2026-02-11 13:30:00', 'US', 'HIGH'),
('US CPI 발표', '미국 소비자물가지수 발표', '2026-03-11 12:30:00', 'US', 'HIGH'),
('US CPI 발표', '미국 소비자물가지수 발표', '2026-04-14 12:30:00', 'US', 'HIGH'),
('US CPI 발표', '미국 소비자물가지수 발표', '2026-05-12 12:30:00', 'US', 'HIGH'),
('US CPI 발표', '미국 소비자물가지수 발표', '2026-06-10 12:30:00', 'US', 'HIGH'),

-- 미국 고용보고서 (Non-Farm Payrolls)
('US 고용보고서 발표', '미국 비농업부문 고용 변동', '2026-01-09 13:30:00', 'US', 'HIGH'),
('US 고용보고서 발표', '미국 비농업부문 고용 변동', '2026-02-06 13:30:00', 'US', 'HIGH'),
('US 고용보고서 발표', '미국 비농업부문 고용 변동', '2026-03-06 13:30:00', 'US', 'HIGH'),
('US 고용보고서 발표', '미국 비농업부문 고용 변동', '2026-04-03 12:30:00', 'US', 'HIGH'),
('US 고용보고서 발표', '미국 비농업부문 고용 변동', '2026-05-08 12:30:00', 'US', 'HIGH'),
('US 고용보고서 발표', '미국 비농업부문 고용 변동', '2026-06-05 12:30:00', 'US', 'HIGH'),

-- 미국 GDP 발표
('US GDP 발표 (1차)', '미국 GDP 성장률 1차 추정치', '2026-01-29 13:30:00', 'US', 'HIGH'),
('US GDP 발표 (1차)', '미국 GDP 성장률 1차 추정치', '2026-04-29 12:30:00', 'US', 'HIGH'),

-- 미국 PCE 발표
('US PCE 물가지수 발표', '미국 개인소비지출 물가지수', '2026-01-30 13:30:00', 'US', 'HIGH'),
('US PCE 물가지수 발표', '미국 개인소비지출 물가지수', '2026-02-27 13:30:00', 'US', 'HIGH'),
('US PCE 물가지수 발표', '미국 개인소비지출 물가지수', '2026-03-27 12:30:00', 'US', 'HIGH'),
('US PCE 물가지수 발표', '미국 개인소비지출 물가지수', '2026-04-30 12:30:00', 'US', 'HIGH'),

-- 한국 기준금리
('한국은행 기준금리 결정', '한국은행 금융통화위원회 기준금리 결정', '2026-01-16 10:00:00', 'KR', 'HIGH'),
('한국은행 기준금리 결정', '한국은행 금융통화위원회 기준금리 결정', '2026-02-27 10:00:00', 'KR', 'HIGH'),
('한국은행 기준금리 결정', '한국은행 금융통화위원회 기준금리 결정', '2026-04-09 10:00:00', 'KR', 'HIGH'),
('한국은행 기준금리 결정', '한국은행 금융통화위원회 기준금리 결정', '2026-05-28 10:00:00', 'KR', 'HIGH'),

-- ISM PMI
('ISM 제조업 PMI 발표', 'ISM 제조업 구매관리자지수', '2026-01-05 15:00:00', 'US', 'MEDIUM'),
('ISM 제조업 PMI 발표', 'ISM 제조업 구매관리자지수', '2026-02-02 15:00:00', 'US', 'MEDIUM'),
('ISM 제조업 PMI 발표', 'ISM 제조업 구매관리자지수', '2026-03-02 15:00:00', 'US', 'MEDIUM'),
('ISM 제조업 PMI 발표', 'ISM 제조업 구매관리자지수', '2026-04-01 14:00:00', 'US', 'MEDIUM'),

-- 미시간 소비자심리지수
('미시간 소비자심리지수 발표', '미시간대학교 소비자심리지수 (확정)', '2026-01-23 15:00:00', 'US', 'MEDIUM'),
('미시간 소비자심리지수 발표', '미시간대학교 소비자심리지수 (확정)', '2026-02-20 15:00:00', 'US', 'MEDIUM'),
('미시간 소비자심리지수 발표', '미시간대학교 소비자심리지수 (확정)', '2026-03-27 14:00:00', 'US', 'MEDIUM');
