spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    locations: classpath:db/migration/mysql

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

server:
  tomcat:
    max-http-form-post-size: 1MB
  max-http-request-header-size: 8KB

logging:
  level:
    com.econdashboard: INFO
